### ISSUE TITLE
Question: format table

### ISSUE THREAD

**Issue by enningb** [jmcnamara/pandas_xlsxwriter_charts#1]
Hi, 
I'm wondering if it's possible to use xlsxwriters-formatting options on the datatable that is written to Excel with pandas to_excel (so not adding a chart, but add formatting (like conditional formatting) to the datatables columns)?

kind regards!

**Comment by jmcnamara** [comment]
Hi,

It isn't possible, yet(1), to add general formatting to an XlsxWriter after the data is written which means that it isn't possible to format the Pandas Excel files unless you use XlsxWriter exclusively to write the data from a dataframe.

However, it is currently possible to add conditional formatting. Just follow one of the Pandas XlsxWriter examples and then apply a conditional format to the data. See the XlsxWriter [Conditional Formatting docs](http://xlsxwriter.readthedocs.org/working_with_conditional_formats.html).

(1) This may change in the future. There is an open feature request for it.

Regards,

John

**Comment by jmcnamara** [comment]
Here is an example of applying conditional formatting:

``` python
import pandas as pd

# Some sample data to plot.
list_data = [30, 40, 50, 40, 20, 10, 5]

# Create a Pandas dataframe from the data.
df = pd.DataFrame(list_data)

# Create a Pandas Excel writer using XlsxWriter as the engine.
excel_file = 'testfile.xlsx'
sheet_name = 'Sheet1'

writer = pd.ExcelWriter(excel_file, engine='xlsxwriter')
df.to_excel(writer, sheet_name=sheet_name)

# Access the XlsxWriter workbook and worksheet objects from the dataframe.
workbook = writer.book
worksheet = writer.sheets[sheet_name]

# Apply a conditional format to the cell range.
worksheet.conditional_format('B2:B8', {'type': '3_color_scale'})

# Close the Pandas Excel writer and output the Excel file.
writer.save()

```

Here is the output:

![screenshot](https://cloud.githubusercontent.com/assets/94267/4569318/c936255e-4f47-11e4-96fc-e426f7da9cdb.png)
