### ISSUE TITLE
Yahoo Finance and Python3 issues

### ISSUE THREAD

**Issue by upthewazoo** [jmcnamara/pandas_xlsxwriter_charts#2]
Python3 you need to change:

(-) for tic, data in all_data.iteritems()})
to
(+) for tic, data in all_data.items()})

Yahoo Finance 404's on the ticker GOOG, but searching finance.yahoo.com for Google there is a separate ticker called GOOGL which works:

(-) for ticker in ['AAPL', 'GOOG', 'IBM', 'YHOO', 'MSFT']:
to
(+) for ticker in ['AAPL', 'GOOGL', 'IBM', 'YHOO', 'MSFT']:

After applying both changes to my local copy of chart_legend_stock.py and chart_stacked_area3.py and these then ran fine without errors for me under Python3 on my system and generated the xlsx documents.

**Comment by jmcnamara** [comment]
Hi,

Thanks for the report.

Both issues are fixed on master now and the docs have been updated.

Regards,

John

**Comment by upthewazoo** [comment]
You are probably a pendantic person much like myself. You have put lot of work making into making beautiful documentation for your XlsxWriter Python package.  To cover the only remaining gap I can find you may want to update the two image files you are using for those two graphs in the documentation as well so as to have congruency between the new stock ticker symbol listed in the updated code for the two Python files and the one that is still displayed in the images in the documentation.

**Comment by jmcnamara** [comment]
> You are probably a pendantic person much like myself.

Indeed. It is par for the course in this business. :-)

> To cover the only remaining gap I can find you may want to update the two image files you are using for those two graphs in the documentation

Done. Thanks.
