### ISSUE TITLE
Question: Ability to export Graph with 2 Y-Axis

### ISSUE THREAD

**Issue by anhdangx** [jmcnamara/pandas_xlsxwriter_charts#3]
Hey guys,
I have 1 question, can we export Graph with 2 Y-Axis? If we can, can you share me an example or any URL in which I can find the answer.
Thank for your supporting!

**Comment by jmcnamara** [comment]
That is possible with XlsxWriter. See the chart [combine()](https://xlsxwriter.readthedocs.io/chart.html#chart-combine) method and the [this example program](https://xlsxwriter.readthedocs.io/example_chart_combined.html).

**Comment by anhdangx** [comment]
Thank you very much @jmcnamara
